<a href="https://colab.research.google.com/github/rpimaster/OAI/blob/main/01-convolution/convolution5-mlps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [2]:
# Prepare samples
samples_inp = torch.tensor([[0.1,0.2,0.3],[0.1,0.1,0.1],[0.4,0.4,0.4],[0.9,0.9,0.9],[0.3,0.2,0.1],[0.0,0.0,0.1],[0.0,0.0,0.0]],dtype=torch.float)
samples_out = torch.tensor([[0.123],[0.111],[0.444],[0.999],[0.321],[0.001],[0.0]],dtype=torch.float)

In [3]:
# ==================================== PERCEPTRON ====================================

In [4]:
class Perceptron(nn.Module):
    # initialization
    def __init__(self, num_inputs, num_hiddens, num_outputs):
        super().__init__()
        self.layer1 = nn.Linear(num_inputs, num_hiddens)
        self.layer2 = nn.Linear(num_hiddens, num_outputs)
    # forward
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [5]:
# Define model
model = Perceptron(3,10,1)

In [6]:
# Define loss function
loss_function = nn.MSELoss(reduction='sum')

In [7]:
# Define optimizer
optimizer = optim.Adam(model.parameters())

In [8]:
# Training
num_epochs = 8000
for t in range(num_epochs):

    # Forward pass
    out = model(samples_inp)
    loss = loss_function(out, samples_out)
    if t % 10 == 0:
        print(t, loss.item())

    # Reset gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update model parameters (weights)
    optimizer.step()

0 3.0978217124938965
10 2.637277126312256
20 2.245349407196045
30 1.9175591468811035
40 1.6453561782836914
50 1.4208154678344727
60 1.2371716499328613
70 1.088227391242981
80 0.9680116176605225
90 0.870625913143158
100 0.7903931140899658
110 0.7222870588302612
120 0.6623794436454773
130 0.608002781867981
140 0.5575703382492065
150 0.5102246999740601
160 0.46551772952079773
170 0.423209011554718
180 0.38316935300827026
190 0.345339298248291
200 0.30970728397369385
210 0.27629372477531433
220 0.245137557387352
230 0.21628421545028687
240 0.1897740662097931
250 0.16563335061073303
260 0.143865704536438
270 0.1244460791349411
280 0.10731695592403412
290 0.09238728880882263
300 0.07953354716300964
310 0.06860416382551193
320 0.05942552164196968
330 0.05180904641747475
340 0.0455593466758728
350 0.04048220068216324
360 0.036391306668519974
370 0.033114053308963776
380 0.030495505779981613
390 0.028400547802448273
400 0.026714637875556946
410 0.025343114510178566
420 0.024209724739193916
430 

In [9]:
# Print weighs
for param in model.parameters():
    print(param.data)

tensor([[ 0.2254, -0.1302, -0.4501],
        [ 0.3820, -0.0988, -0.1062],
        [-0.1838, -0.1807,  0.2620],
        [-0.9045,  0.0525, -0.4993],
        [ 0.4579, -0.0398, -0.7142],
        [-0.0694, -0.1938, -0.2081],
        [ 0.0375,  0.2689,  0.4732],
        [-0.5186, -0.2308,  0.0644],
        [-0.4520,  0.4984, -0.1949],
        [-0.7207, -0.2013,  0.0143]])
tensor([-0.3535, -0.5505, -0.0300, -0.2465, -0.1524, -0.3600,  0.1318,  0.0355,
        -0.4990,  0.1744])
tensor([[ 0.0168, -0.0714, -0.0392, -0.3861,  0.4172,  0.1284,  0.3029, -0.2783,
         -0.0533, -0.3871]])
tensor([-0.0085])


In [10]:
# Test
result = model(torch.tensor([[0.7,0.8,0.9]],dtype=torch.float))
print('test result',round(result[0].item(),3))

test result 0.789


In [11]:
# ================ PERCEPTRONS RUNNING IN PARALLEL AND SHARING WEIGHTS ================

In [12]:
samples_inp = samples_inp.unsqueeze(-1).unsqueeze(-1)
samples_out = samples_out.unsqueeze(-1).unsqueeze(-1)

In [13]:
class FCPerceptron(nn.Module):
    # initialization
    def __init__(self, num_inputs, num_hiddens, num_outputs):
        super().__init__()
        self.layer1 = nn.Conv2d(num_inputs, num_hiddens, (1,1))
        self.layer2 = nn.Conv2d(num_hiddens, num_outputs, (1,1))
    # forward
    def forward(self, x):
        return self.layer2(self.layer1(x))

In [14]:
# Define model
model = FCPerceptron(3,10,1)

In [15]:
# Define loss function
loss_function = nn.MSELoss(reduction='sum')

In [16]:
# Define optimizer
optimizer = optim.Adam(model.parameters())

In [17]:
# Training
num_epochs = 8000
for t in range(num_epochs):

    # Forward pass
    out = model(samples_inp)
    loss = loss_function(out, samples_out)
    if t % 10 == 0:
        print(t, loss.item())

    # Reset gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update model parameters (weights)
    optimizer.step()

0 0.4874378740787506
10 0.3816520869731903
20 0.29092937707901
30 0.2149071991443634
40 0.15285176038742065
50 0.10396533459424973
60 0.06717033684253693
70 0.04100271314382553
80 0.02365284040570259
90 0.01307821273803711
100 0.00723873358219862
110 0.004358727019280195
120 0.0031048250384628773
130 0.0026213836390525103
140 0.0024441969580948353
150 0.0023640054278075695
160 0.002305173547938466
170 0.00224771979264915
180 0.002189068356528878
190 0.002129925647750497
200 0.0020708164665848017
210 0.002011876320466399
220 0.0019531529396772385
230 0.0018946961499750614
240 0.0018366031581535935
250 0.0017789570847526193
260 0.0017218556022271514
270 0.0016653832281008363
280 0.0016096151666715741
290 0.0015546234790235758
300 0.0015004787128418684
310 0.0014472368638962507
320 0.0013949539279565215
330 0.0013436810113489628
340 0.0012934631668031216
350 0.0012443391606211662
360 0.0011963436845690012
370 0.0011495095677673817
380 0.0011038609081879258
390 0.0010594220366328955
400 0.

In [18]:
# Print weighs
for param in model.parameters():
    print(param.data)

tensor([[[[ 0.3886]],

         [[-0.1067]],

         [[ 0.3169]]],


        [[[ 0.5492]],

         [[ 0.5199]],

         [[-0.4403]]],


        [[[-0.2575]],

         [[-0.4702]],

         [[ 0.2964]]],


        [[[ 0.7246]],

         [[ 0.5853]],

         [[ 0.2599]]],


        [[[-0.4349]],

         [[-0.3308]],

         [[ 0.2748]]],


        [[[ 0.4210]],

         [[ 0.4848]],

         [[ 0.2495]]],


        [[[-0.4197]],

         [[ 0.1762]],

         [[-0.2577]]],


        [[[ 0.6297]],

         [[ 0.5030]],

         [[-0.2966]]],


        [[[ 0.6032]],

         [[-0.4008]],

         [[-0.2273]]],


        [[[-0.3014]],

         [[-0.1962]],

         [[-0.3502]]]])
tensor([-0.3280, -0.4280, -0.5640, -0.0177, -0.0755,  0.3732,  0.0696,  0.2344,
         0.0675, -0.2300])
tensor([[[[ 0.3765]],

         [[ 0.2214]],

         [[ 0.1136]],

         [[ 0.1146]],

         [[-0.3490]],

         [[-0.0240]],

         [[-0.1746]],

         [[ 0.1159]],



In [19]:
# Test
result = model(torch.tensor([[[[0.7]],[[0.8]],[[0.9]]]],dtype=torch.float))
print('test result',round(result[0].item(),3))

test result 0.789


In [20]:
# Run in parallel 3 x 3 perceptrons that share weights
data = torch.tensor([[[[0.7,0.8,0.9],[0.4,0.5,0.6],[0.1,0.2,0.3]],[[0.7,0.8,0.8],[0.4,0.5,0.5],[0.1,0.2,0.2]],[[0.7,0.8,0.1],[0.4,0.4,0.4],[0.1,0.2,0.1]]]],dtype=torch.float)
result = model(data.permute(0,3,1,2))
import numpy as np
print('test result:\n',np.round(result[0].detach().cpu().numpy(),3))

test result:
 [[[0.789 0.456 0.123]
  [0.788 0.455 0.122]
  [0.781 0.444 0.121]]]
